name: Deploy Laravel API to Shared Hosting

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, pdo_mysql, bcmath

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: payment-api.cns.ug/
        exclude: |
          **/.git*/**
          **/.github*/**
          **/tests*/**

    - name: Rename .env
      run: mv .env.example .env

    - name: Inject Production Environment Variables
      run: |
        echo "APP_ENV=production" >> .env
        echo "APP_URL=${{ secrets.BACKEND_APP_URL }}" >> .env
        echo "FRONTEND_URL=${{ secrets.CLIENT_APP_URL }}" >> .env
        echo "DB_CONNECTION=mariadb" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Generate Application Key
      run: php artisan key:generate --force 

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Laravel Optimizations 
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
