name: Deploy Laravel API to Shared Hosting

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, pdo_mysql, bcmath

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Clean .env
      run: rm -f .env
      
    - name: Inject Production Environment Variables
      run: |
        echo "APP_ENV=production" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
        echo "APP_URL=${{ secrets.BACKEND_APP_URL }}" >> .env
        echo "FRONTEND_URL=${{ secrets.CLIENT_APP_URL }}" >> .env
        echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "SANCTUM_STATEFUL_DOMAINS=${{ secrets.CLIENT_APP_URL }}" >> .env
        echo "SESSION_DOMAIN=${{ secrets.SESSION_DOMAIN }}" >> .env
        echo "SESSION_SECURE_COOKIE=true" >> .env

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.DIRECTORY }}
        exclude: |
          **/.git*/**
          **/.github*/**
          **/tests*/**
          payment_db.sql
          deploy.yaml

    - name: Run Laravel Optimizations
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
